// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UFgXptzECYj6pS2yNNMDFStVXdkYo-A',
    appId: '1:773125965993:web:ee0d0a1baa4c974ac881b8',
    messagingSenderId: '773125965993',
    projectId: 'crudappnotes',
    authDomain: 'crudappnotes.firebaseapp.com',
    storageBucket: 'crudappnotes.firebasestorage.app',
    measurementId: 'G-2N4BRC13DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFoZxdBJtK2cPRMO07RMedSiklfneG44Y',
    appId: '1:773125965993:android:7bbf5f530903ecf3c881b8',
    messagingSenderId: '773125965993',
    projectId: 'crudappnotes',
    storageBucket: 'crudappnotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcdJEMGIMbScy3Wsirwaf2J61kqpG2z5o',
    appId: '1:773125965993:ios:bc5b6e743b371e08c881b8',
    messagingSenderId: '773125965993',
    projectId: 'crudappnotes',
    storageBucket: 'crudappnotes.firebasestorage.app',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5UFgXptzECYj6pS2yNNMDFStVXdkYo-A',
    appId: '1:773125965993:web:cf0d9f87454ed340c881b8',
    messagingSenderId: '773125965993',
    projectId: 'crudappnotes',
    authDomain: 'crudappnotes.firebaseapp.com',
    storageBucket: 'crudappnotes.firebasestorage.app',
    measurementId: 'G-R5HG76EC3D',
  );
}
